name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install
        working-directory: node-nginx-app/app

      - name: Lint or Test Placeholder
        run: echo "No tests yet"

      - name: Build Docker image
        run: docker build -t devops-app .
        working-directory: node-nginx-app
